api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes and configures the New Relic Agent"
  homepage = "https://github.com/dpacheconr/newrelic-java-paketo-buildpack"
  id = "newrelic/java-agent"
  keywords = ["java"]
  version = "1.0.0"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]

[metadata]
  include-files = ["README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "Enable the New Relic Agent"
    name = "BP_NEW_RELIC_ENABLED"


  # To use different version NR agent, update uri and version variables accordingly
  [[metadata.dependencies]]
    id = "nr-agent-java"
    name = "New Relic Java Agent"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://download.newrelic.com/newrelic/java-agent/newrelic-agent/7.8.0/newrelic-agent-7.8.0.jar"
    version = "7.8.0"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
